/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.SPchitietDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SPchitiet;
import repository.SPchiTietRepo;
import repository.SanPhamRepo;

/**
 *
 * @author Admin
 */
public class SPchitietView extends javax.swing.JPanel {
    private SPchiTietRepo repo = new SPchiTietRepo();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;
    /**
     * Creates new form SPchitietView
     */
    public SPchitietView() {
        initComponents();
        this.filltotable(repo.getall());
        loadcombobox();
    }

    void filltotable(ArrayList<SPchitiet> list){
        mol = (DefaultTableModel) tblSPchitiet.getModel();
        mol.setRowCount(0);
        for (SPchitiet sPchitiet : list) {
            mol.addRow(sPchitiet.addtorow());
        }
    }
    void showdata(int i){
        txtmaspct.setText(tblSPchitiet.getValueAt(i, 1).toString());
        cbbIDSP.setSelectedItem(tblSPchitiet.getValueAt(i, 2).toString());
        cbbIDMS.setSelectedItem(tblSPchitiet.getValueAt(i, 3).toString());
        cbbIDKT.setSelectedItem(tblSPchitiet.getValueAt(i, 4).toString());
        txtSoluongton.setText(tblSPchitiet.getValueAt(i, 5).toString());
        txtGiaBan.setText(tblSPchitiet.getValueAt(i, 6).toString());
    }
    
    void loadcombobox() {
        SPchitietDAO dao = new SPchitietDAO();
        
        cbbIDSP.removeAllItems();
        for (String item : dao.getProductList()) {
            cbbIDSP.addItem(item); 
        }
        
        cbbIDMS.removeAllItems();
        for (String item : dao.getCOLORList()) {
            cbbIDMS.addItem(item);
        }
        
        cbbIDKT.removeAllItems();
        for (String item : dao.getSIZEList()) {
            cbbIDKT.addItem(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSPchitiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtmaspct = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoluongton = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbIDSP = new javax.swing.JComboBox<>();
        cbbIDMS = new javax.swing.JComboBox<>();
        cbbIDKT = new javax.swing.JComboBox<>();
        btnADD = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnXoamem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblspctdaremove = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        tblSPchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ma spchitiet", "id_sanpham", "id_mausac", "id_kichthuoc", "soluong", "gia", "trangthai"
            }
        ));
        tblSPchitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPchitietMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSPchitiet);

        jLabel1.setText("ma spct");

        jLabel2.setText("id_sanpham");

        jLabel3.setText("id_mausac");

        jLabel4.setText("gia");

        jLabel5.setText("soluong");

        jLabel6.setText("id_kichthuoc");

        btnADD.setText("add");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnUPDATE.setText("update");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnXoamem.setText("Ẩn");
        btnXoamem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoamemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtmaspct, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbIDSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbIDMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(108, 108, 108)
                        .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnXoamem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtSoluongton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbbIDKT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaspct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbIDMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoamem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbIDKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoluongton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("sản phẩm chi tiết", jPanel1);

        tblspctdaremove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ma spchitiet", "id_sanpham", "id_mausac", "id_kichthuoc", "soluong", "gia", "trangthai"
            }
        ));
        tblspctdaremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspctdaremoveMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblspctdaremove);

        jButton1.setText("hiện");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSPchitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPchitietMouseClicked
        // TODO add your handling code here:
        i = tblSPchitiet.getSelectedRow();
        showdata(i);
    }//GEN-LAST:event_tblSPchitietMouseClicked

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        if (repo.add(this.readform()) > 0) {
            JOptionPane.showMessageDialog(this, "lưu thành công");
            this.filltotable(repo.getall());
        } else {
            JOptionPane.showMessageDialog(this, "lưu thất bại");
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
        i = tblSPchitiet.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần update");
        } else {
            String ma = txtmaspct.getText();
            SPchitiet sp = this.readform();
            if (sp != null) {
                if (repo.update(sp, ma) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    this.filltotable(repo.getall());
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnXoamemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoamemActionPerformed
        // TODO add your handling code here:
        int i = tblSPchitiet.getSelectedRow(); // Lấy dòng đang chọn
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ma = txtmaspct.getText(); // Lấy mã màu từ ô nhập liệu

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn ẩn spct này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (repo.remove(ma) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filltotable(repo.getall()); // Cập nhật bảng sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn mục cần ẩn!", "Lỗi", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnXoamemActionPerformed

    private void tblspctdaremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspctdaremoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblspctdaremoveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JButton btnXoamem;
    private javax.swing.JComboBox<String> cbbIDKT;
    private javax.swing.JComboBox<String> cbbIDMS;
    private javax.swing.JComboBox<String> cbbIDSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblSPchitiet;
    private javax.swing.JTable tblspctdaremove;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtSoluongton;
    private javax.swing.JTextField txtmaspct;
    // End of variables declaration//GEN-END:variables

    SPchitiet readform(){
        String maspct;
        int idproduct, idcolor, idsize, soluong;
        Long gia;
        maspct= txtmaspct.getText();
        idproduct = Integer.parseInt(cbbIDSP.getSelectedItem().toString()); 
        idcolor = Integer.parseInt(cbbIDMS.getSelectedItem().toString()); 
        idsize = Integer.parseInt(cbbIDKT.getSelectedItem().toString()); 
        soluong = Integer.parseInt(txtSoluongton.getText()); 
        gia = Long.parseLong(txtGiaBan.getText());
        return new SPchitiet(i, maspct, idproduct, idcolor, idsize, soluong, gia, Boolean.TRUE);
    }
}
