/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Kichthuoc;
import model.Loaisanpham;
import repository.MauSacRepo;
import model.Mausac;
import repository.KichthuocRepo;
import repository.LoaiSanPhamRepo;

/**
 *
 * @author Admin
 */
public class ThuocTinhView extends javax.swing.JPanel {

    private MauSacRepo rp = new MauSacRepo();
    private KichthuocRepo rep = new KichthuocRepo();
    private LoaiSanPhamRepo repo = new LoaiSanPhamRepo();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;

    /**
     * Creates new form MauSacView
     */
    public ThuocTinhView() {
        initComponents();
        this.filltotablems(rp.getallms());
        this.filltotablekt(rep.getallkt());
        this.filltotablelsp(repo.getalllsp());
    }

    public void filltotablems(ArrayList<Mausac> list) {
        mol = (DefaultTableModel) tblMauSac.getModel();
        mol.setRowCount(0);
        for (Mausac mausac : list) {
            mol.addRow(mausac.addtorow());
        }
    }

    public void filltotablekt(ArrayList<Kichthuoc> list) {
        mol = (DefaultTableModel) tblkichthuoc.getModel();
        mol.setRowCount(0);
        for (Kichthuoc kichthuoc : list) {
            mol.addRow(kichthuoc.addtorow());
        }
    }

    public void filltotablelsp(ArrayList<Loaisanpham> list) {
        mol = (DefaultTableModel) tblLoaisanpham.getModel();
        mol.setRowCount(0);
        for (Loaisanpham loaisanpham : list) {
            mol.addRow(loaisanpham.addtorow());
        }
    }

    void showdatams(int i) {
        txtmams.setText(tblMauSac.getValueAt(i, 1).toString());
        txtTenms.setText(tblMauSac.getValueAt(i, 2).toString());
        Boolean trangThai = (Boolean) tblMauSac.getValueAt(i, 3);

        if (Boolean.TRUE.equals(trangThai)) {
            rdbkichhoatms.setSelected(true);
        } else {
            rdbvohieums.setSelected(true);
        }
    }

    void showdatakt(int i) {
        txtMaKichthuoc.setText(tblkichthuoc.getValueAt(i, 1).toString());
        txtTenKichthuoc.setText(tblkichthuoc.getValueAt(i, 2).toString());
        Boolean trangThaikt = (Boolean) tblkichthuoc.getValueAt(i, 3);

        if (Boolean.TRUE.equals(trangThaikt)) {
            rdbKichhoatKT.setSelected(true);
        } else {
            rdbVohieuKT.setSelected(true);
        }
    }

    void showdatalsp(int i) {
        txtMaLoaisp.setText(tblLoaisanpham.getValueAt(i, 1).toString());
        txtTenLoaisp.setText(tblLoaisanpham.getValueAt(i, 2).toString());
        Boolean trangThailsp = (Boolean) tblLoaisanpham.getValueAt(i, 3);

        if (Boolean.TRUE.equals(trangThailsp)) {
            rdbkichhoatLSP.setSelected(true);
        } else {
            rdbvohieuLSP.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmams = new javax.swing.JTextField();
        txtTenms = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnThemMS = new javax.swing.JButton();
        btnUpdateMS = new javax.swing.JButton();
        btnXoaMS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMauSac = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        rdbkichhoatms = new javax.swing.JRadioButton();
        rdbvohieums = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKichthuoc = new javax.swing.JTextField();
        txtTenKichthuoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnThemKT = new javax.swing.JButton();
        btnUpdateKT = new javax.swing.JButton();
        btnXoaKT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblkichthuoc = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        rdbKichhoatKT = new javax.swing.JRadioButton();
        rdbVohieuKT = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaLoaisp = new javax.swing.JTextField();
        txtTenLoaisp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThemLSP = new javax.swing.JButton();
        btnUpdateLSP = new javax.swing.JButton();
        btnXoaLSP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoaisanpham = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        rdbkichhoatLSP = new javax.swing.JRadioButton();
        rdbvohieuLSP = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Mã màu sắc");

        jLabel2.setText("Tên màu sắc");

        btnThemMS.setText("add");
        btnThemMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMSActionPerformed(evt);
            }
        });

        btnUpdateMS.setText("update");
        btnUpdateMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMSActionPerformed(evt);
            }
        });

        btnXoaMS.setText("hide");
        btnXoaMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMSActionPerformed(evt);
            }
        });

        tblMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "mã màu sắc", "tên màu sắc", "trạng thái"
            }
        ));
        tblMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMauSacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMauSac);

        jLabel7.setText("Trạng thái");

        buttonGroup1.add(rdbkichhoatms);
        rdbkichhoatms.setText("kích hoạt");

        buttonGroup1.add(rdbvohieums);
        rdbvohieums.setText("vô hiệu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmams, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenms, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThemMS)
                                .addGap(29, 29, 29)
                                .addComponent(btnUpdateMS))
                            .addComponent(btnXoaMS)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbvohieums)
                            .addComponent(rdbkichhoatms))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtmams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemMS)
                            .addComponent(btnUpdateMS))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaMS))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(rdbkichhoatms))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbvohieums))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("mã kích thước");

        jLabel4.setText("Tên kích thước");

        btnThemKT.setText("add");
        btnThemKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKTActionPerformed(evt);
            }
        });

        btnUpdateKT.setText("update");
        btnUpdateKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKTActionPerformed(evt);
            }
        });

        btnXoaKT.setText("hide");
        btnXoaKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKTActionPerformed(evt);
            }
        });

        tblkichthuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "mã kích thước", "tên kích thước", "trạng thái"
            }
        ));
        tblkichthuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkichthuocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblkichthuoc);

        jLabel8.setText("Trạng thái");

        buttonGroup2.add(rdbKichhoatKT);
        rdbKichhoatKT.setText("kích hoạt");

        buttonGroup2.add(rdbVohieuKT);
        rdbVohieuKT.setText("vô hiệu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaKichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenKichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThemKT)
                                .addGap(29, 29, 29)
                                .addComponent(btnUpdateKT))
                            .addComponent(btnXoaKT)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbVohieuKT)
                            .addComponent(rdbKichhoatKT))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaKichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemKT)
                            .addComponent(btnUpdateKT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenKichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaKT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(rdbKichhoatKT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbVohieuKT))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("mã loại sản phẩm");

        jLabel6.setText("tên loại sản phẩm");

        btnThemLSP.setText("add");
        btnThemLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLSPActionPerformed(evt);
            }
        });

        btnUpdateLSP.setText("update");
        btnUpdateLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLSPActionPerformed(evt);
            }
        });

        btnXoaLSP.setText("hide");
        btnXoaLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLSPActionPerformed(evt);
            }
        });

        tblLoaisanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "mã loại sản phẩm", "tên màu sắc", "trạng thái"
            }
        ));
        tblLoaisanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaisanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLoaisanpham);

        jLabel9.setText("Trạng thái");

        buttonGroup3.add(rdbkichhoatLSP);
        rdbkichhoatLSP.setText("kích hoạt");

        buttonGroup3.add(rdbvohieuLSP);
        rdbvohieuLSP.setText("vô hiệu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenLoaisp, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtMaLoaisp)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbvohieuLSP)
                            .addComponent(rdbkichhoatLSP))))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateLSP)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnThemLSP)
                        .addComponent(btnXoaLSP)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateLSP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThemLSP)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaLSP))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTenLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbkichhoatLSP)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbvohieuLSP))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMauSacMouseClicked
        // TODO add your handling code here:
        i = tblMauSac.getSelectedRow();
        showdatams(i);
    }//GEN-LAST:event_tblMauSacMouseClicked

    private void btnThemMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMSActionPerformed
        // TODO add your handling code here:
        Mausac mausac = readformms();

        if (mausac.getMamausac().isEmpty() || mausac.getTenmausac().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rp.addms(mausac) > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            filltotablems(rp.getallms()); // Cập nhật bảng ngay sau khi thêm
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemMSActionPerformed

    private void btnUpdateMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMSActionPerformed
        // TODO add your handling code here:
        i = tblMauSac.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần update");
        } else {
            String ma = txtmams.getText();
            Mausac ms = this.readformms();
            if (ms != null) {
                if (rp.updatems(ms, ma) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    this.filltotablems(rp.getallms());
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateMSActionPerformed

    private void btnXoaMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMSActionPerformed
        // TODO add your handling code here:

        int i = tblMauSac.getSelectedRow(); // Lấy dòng đang chọn
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn màu sắc cần xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ma = txtmams.getText(); // Lấy mã màu từ ô nhập liệu

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa màu sắc này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (rp.deletems(ma) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filltotablems(rp.getallms()); // Cập nhật bảng sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnXoaMSActionPerformed

    private void btnThemKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKTActionPerformed
        // TODO add your handling code here:
        Kichthuoc size = readformkt();

        if (size.getMakichthuoc().isEmpty() || size.getTenkichthuoc().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rep.addkt(size) > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            filltotablekt(rep.getallkt()); // Cập nhật bảng ngay sau khi thêm
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemKTActionPerformed

    private void btnUpdateKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKTActionPerformed
        // TODO add your handling code here:
        i = tblkichthuoc.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần update");
        } else {
            String ma = txtMaKichthuoc.getText();
            Kichthuoc kt = this.readformkt();
            if (kt != null) {
                if (rep.updatekt(kt, ma) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    this.filltotablekt(rep.getallkt());
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateKTActionPerformed

    private void btnXoaKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKTActionPerformed
        // TODO add your handling code here:
        int i = tblkichthuoc.getSelectedRow(); // Lấy dòng đang chọn
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn màu sắc cần xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ma = txtMaKichthuoc.getText(); // Lấy mã màu từ ô nhập liệu

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa màu sắc này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (rep.deletekt(ma) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filltotablekt(rep.getallkt()); // Cập nhật bảng sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaKTActionPerformed

    private void tblkichthuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkichthuocMouseClicked
        // TODO add your handling code here:
        i = tblkichthuoc.getSelectedRow();
        showdatakt(i);
    }//GEN-LAST:event_tblkichthuocMouseClicked

    private void btnThemLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLSPActionPerformed
        // TODO add your handling code here:
        Loaisanpham lsp = readformlsp();

        if (lsp.getMalsp().isEmpty() || lsp.getTenlsp().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (repo.addlsp(lsp) > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            filltotablelsp(repo.getalllsp()); // Cập nhật bảng ngay sau khi thêm
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemLSPActionPerformed

    private void btnUpdateLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLSPActionPerformed
        // TODO add your handling code here:
        i = tblLoaisanpham.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần update");
        } else {
            String ma = txtMaLoaisp.getText();
            Loaisanpham lsp = this.readformlsp();
            if (lsp != null) {
                if (repo.updatelsp(lsp, ma) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    this.filltotablelsp(repo.getalllsp());
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateLSPActionPerformed

    private void btnXoaLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLSPActionPerformed
        // TODO add your handling code here:
        int i = tblLoaisanpham.getSelectedRow(); // Lấy dòng đang chọn
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn màu sắc cần xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ma = txtMaLoaisp.getText(); // Lấy mã màu từ ô nhập liệu

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa màu sắc này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (repo.deletelsp(ma) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filltotablelsp(repo.getalllsp()); // Cập nhật bảng sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaLSPActionPerformed

    private void tblLoaisanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaisanphamMouseClicked
        // TODO add your handling code here:
        i = tblLoaisanpham.getSelectedRow();
        showdatalsp(i);
    }//GEN-LAST:event_tblLoaisanphamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemKT;
    private javax.swing.JButton btnThemLSP;
    private javax.swing.JButton btnThemMS;
    private javax.swing.JButton btnUpdateKT;
    private javax.swing.JButton btnUpdateLSP;
    private javax.swing.JButton btnUpdateMS;
    private javax.swing.JButton btnXoaKT;
    private javax.swing.JButton btnXoaLSP;
    private javax.swing.JButton btnXoaMS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdbKichhoatKT;
    private javax.swing.JRadioButton rdbVohieuKT;
    private javax.swing.JRadioButton rdbkichhoatLSP;
    private javax.swing.JRadioButton rdbkichhoatms;
    private javax.swing.JRadioButton rdbvohieuLSP;
    private javax.swing.JRadioButton rdbvohieums;
    private javax.swing.JTable tblLoaisanpham;
    private javax.swing.JTable tblMauSac;
    private javax.swing.JTable tblkichthuoc;
    private javax.swing.JTextField txtMaKichthuoc;
    private javax.swing.JTextField txtMaLoaisp;
    private javax.swing.JTextField txtTenKichthuoc;
    private javax.swing.JTextField txtTenLoaisp;
    private javax.swing.JTextField txtTenms;
    private javax.swing.JTextField txtmams;
    // End of variables declaration//GEN-END:variables

    Mausac readformms() {
        String mams;
        String tenms;
        Boolean trangthai = true;
        mams = txtmams.getText();
        tenms = txtTenms.getText();
        return new Mausac(0, mams, tenms, trangthai);
    }

    Kichthuoc readformkt() {
        String makt;
        String tenkt;
        Boolean trangthai = true;
        makt = txtMaKichthuoc.getText();
        tenkt = txtTenKichthuoc.getText();
        return new Kichthuoc(0, makt, tenkt, trangthai);
    }

    Loaisanpham readformlsp() {
        String malsp;
        String tenlsp;
        Boolean trangthai = true;
        malsp = txtMaLoaisp.getText();
        tenlsp = txtTenLoaisp.getText();
        return new Loaisanpham(i, malsp, tenlsp, trangthai);
    }

}
